services:
  mongodb:
    image: mongo:latest
    container_name: calm_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ../mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - calm-net
  calmhub:
    build:
      context: ..
      dockerfile: src/main/docker/Dockerfile.jvm
    image: calm-hub:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dquarkus.mongodb.connection-string=mongodb://mongodb:27017
    networks:
      - calm-net
networks:
  calm-net:
    driver: bridge