name: Build CALM Explorer

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
    push:
        branches:
            - 'main'

jobs:
    calm-explorer:
        name: Build, Test, and Lint CALM Explorer
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

            - name: Setup Node.js
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
              with:
                  node-version: v22

            - name: Install workspace
              run: npm ci

            - name: Lint Module
              run: npm run lint --workspace=experimental/calm-explorer

            - name: Build workspace
              run: npm run build --workspace=experimental/calm-explorer

            - name: Run tests
              run: npm run test:run --workspace=experimental/calm-explorer
