name: Build CLI

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
            - 'release*'
    push:
        branches:
            - 'main'
            - 'release*'

jobs:
    cli:
        name: Build, Test, and Lint CLI Module
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Setup Node.js
              uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
              with:
                  node-version: v22

            - name: Install workspace
              run: npm ci

            - name: Lint CLI Module
              run: npm run lint --workspace=cli

            - name: Build workspace
              run: npm run build:cli

            - name: Run tests with coverage for CLI
              run: npm run test --workspace=cli
