name: Build Docs

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
            - 'release*'
    push:
        branches:
            - 'main'
            - 'release*'

jobs:
    docs:
        name: Build Docs Module
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Setup Node.js
              uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
              with:
                  node-version: v22
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install workspace
              run: npm ci

            - name: Build Docs
              run: npm run build:docs
