name: Build Calm Hub with Integration Tests and Coverage

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
            - 'release*'
    push:
        branches:
            - 'main'
            - 'release*'

jobs:
    build:
        name: Build Calm Hub
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout PR Branch
            - name: Checkout PR Branch
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

            # Step 2: Set up JDK
            - name: Set up JDK
              uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
              with:
                  distribution: 'temurin'
                  java-version: '21'

            # Step 3: Cache Maven Dependencies
            - name: Cache Maven Dependencies
              uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('calm-hub/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-m2-

            # Step 4: Set up Docker (Required for Testcontainers)
            - name: Set up Docker
              uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

            # Step 5: Build and Test
            - name: Build and Test
              working-directory: calm-hub
              run: mvn -P integration clean verify -Ddependency-check.skip=true
