name: Build Calm Widgets

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
            - 'release*'
    push:
        branches:
            - 'main'
            - 'release*'

jobs:
    shared:
        name: Build, Test, and Lint Calm Widgets Module
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

            - name: Setup Node.js
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
              with:
                  node-version: v22

            - name: Install workspace
              run: npm ci

            - name: Lint Shared Module
              run: npm run lint --workspace=calm-widgets

            - name: Build workspace
              run: npm run build:calm-widgets

            - name: Run tests with coverage for Calm Widgets
              run: npm run test:calm-widgets
