name: Build Calm Hub with Integration Tests and Coverage

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
            - 'release*'
    push:
        branches:
            - 'main'
            - 'release*'

jobs:
    build:
        name: Build Calm Hub
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout PR Branch
            - name: Checkout PR Branch
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            # Step 2: Set up JDK
            - name: Set up JDK
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
              with:
                  distribution: 'temurin'
                  java-version: '21'

            # Step 3: Cache Maven Dependencies
            - name: Cache Maven Dependencies
              uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('calm-hub/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-m2-

            # Step 4: Set up Docker (Required for Testcontainers)
            - name: Set up Docker
              uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

            # Step 5: Build and Test
            - name: Build and Test
              working-directory: calm-hub
              run: mvn -P integration clean verify -Ddependency-check.skip=true
