name: Build Shared

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
            - 'release*'
    push:
        branches:
            - 'main'
            - 'release*'

jobs:
    shared:
        name: Build, Test, and Lint Shared Module
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

            - name: Setup Node.js
              uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
              with:
                  node-version: v22

            - name: Install workspace
              run: npm ci

            - name: Lint Shared Module
              run: npm run lint --workspace=shared

            - name: Build workspace
              run: npm run build:shared

            - name: Run tests with coverage for Shared
              run: npm run test --workspace=shared
