name: Build Docs

permissions:
    contents: read

on:
    pull_request:
        branches:
            - 'main'
            - 'release*'
    push:
        branches:
            - 'main'
            - 'release*'

jobs:
    docs:
        name: Build Docs Module
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR Branch
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

            - name: Setup Node.js
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
              with:
                  node-version: v22
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install workspace
              run: npm ci

            - name: Build Docs
              run: npm run build:docs
