name: Sync CALM to S3

permissions:
    contents: read

on:
    workflow_dispatch: {}
    push:
        branches:
            - main
        paths:
            - 'calm/controls/**'
            - 'calm/draft/**'
            - 'calm/getting-started/**'
            - 'calm/interfaces/**'
            - 'calm/release/**'

jobs:
    sync-to-s3:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
              with:
                  aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Sync calm/draft folder to S3
              run: |
                  aws s3 sync calm/draft s3://${{ vars.AWS_S3_BUCKET }}/draft --delete
            - name: Sync calm/release folder to S3
              run: |
                  aws s3 sync calm/release s3://${{ vars.AWS_S3_BUCKET }}/release --delete
            - name: Sync calm/getting-started folder to S3
              run: |
                  aws s3 sync calm/getting-started s3://${{ vars.AWS_S3_BUCKET }}/getting-started --delete
            - name: Sync calm/interfaces folder to S3
              run: |
                  aws s3 sync calm/interfaces s3://${{ vars.AWS_S3_BUCKET }}/interfaces --delete
            - name: Sync calm/controls folder to S3
              run: |
                  aws s3 sync calm/controls s3://${{ vars.AWS_S3_BUCKET }}/controls --delete
